//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proptiwise.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class application_details
    {
        public application_details()
        {
            this.TenancyDetails = new HashSet<TenancyDetail>();
        }
    
        public int ApplicationId { get; set; }
        public string FullName { get; set; }
        public string FormerName { get; set; }
        public string PhoneNumber { get; set; }
        public string MobileNumber { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public Nullable<int> Nationality { get; set; }
        public string MaritalStatus { get; set; }
        public Nullable<int> Children { get; set; }
        public Nullable<int> Notolive { get; set; }
        public string PeopleNames { get; set; }
        public Nullable<int> Noage18 { get; set; }
        public Nullable<bool> Pets { get; set; }
        public Nullable<bool> Smoker { get; set; }
        public string fullnames { get; set; }
        public string HouseNumber { get; set; }
        public string StreetName { get; set; }
        public string Town { get; set; }
        public string City { get; set; }
        public string Country { get; set; }
        public string PostCode { get; set; }
        public Nullable<System.DateTime> Moveindate { get; set; }
        public Nullable<System.DateTime> Moveout { get; set; }
        public string Address { get; set; }
        public string ReferenceName { get; set; }
        public string ReferneceNumber { get; set; }
        public string ReferenceEmail { get; set; }
        public string Employmntstatus { get; set; }
        public string EmployerName { get; set; }
        public string Emphousenum { get; set; }
        public string Empstreetname { get; set; }
        public string Emptown { get; set; }
        public string EmpCity { get; set; }
        public string EmpCountry { get; set; }
        public string EmpPostCode { get; set; }
        public string Phone { get; set; }
        public string EmpEmail { get; set; }
        public string Position { get; set; }
        public string LengthEmp { get; set; }
        public string CPName { get; set; }
        public string CPNumber { get; set; }
        public string CPemail { get; set; }
        public Nullable<double> NetIncome { get; set; }
        public Nullable<double> AddIncome { get; set; }
        public Nullable<double> GrossIncome { get; set; }
        public Nullable<bool> countryagainst { get; set; }
        public Nullable<bool> bankruptcy { get; set; }
        public Nullable<bool> criminalactivity { get; set; }
        public Nullable<bool> terroristactivity { get; set; }
        public string netduration { get; set; }
        public string additionalduration { get; set; }
        public string grossduration { get; set; }
        public Nullable<long> PropertyId { get; set; }
        public Nullable<long> TenantId { get; set; }
        public Nullable<long> LandlordId { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<int> SentStatus { get; set; }
        public Nullable<int> FillStatus { get; set; }
        public string CmtRejected { get; set; }
        public string CmtDeffered { get; set; }
    
        public virtual Property Property { get; set; }
        public virtual Tenant Tenant { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<TenancyDetail> TenancyDetails { get; set; }
    }
}
