//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proptiwise.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Applicant
    {
        public int Applicant_Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Telephone { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public string SSN { get; set; }
        public string Desired_Property { get; set; }
        public Nullable<System.DateTime> Received_On { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public string Gender { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string PostCode { get; set; }
        public Nullable<System.DateTime> Dateofbirth { get; set; }
        public string DriverLicense { get; set; }
        public string SocialSecurity { get; set; }
        public Nullable<int> Profile { get; set; }
        public Nullable<bool> Smoker { get; set; }
        public string Comment { get; set; }
        public Nullable<long> Landlord_Id { get; set; }
    
        public virtual ApprovalStatus ApprovalStatus { get; set; }
    }
}
