//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proptiwise.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApprovalStatus
    {
        public ApprovalStatus()
        {
            this.Applicants = new HashSet<Applicant>();
        }
    
        public int ApprovalStatus_Id { get; set; }
        public string ApprovalStatus1 { get; set; }
    
        public virtual ICollection<Applicant> Applicants { get; set; }
    }
}
