//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proptiwise.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Building
    {
        public Building()
        {
            this.damage_intventory = new HashSet<damage_intventory>();
            this.paymentHistories = new HashSet<paymentHistory>();
            this.tbl_inventory = new HashSet<tbl_inventory>();
            this.Properties = new HashSet<Property>();
        }
    
        public int Building_Id { get; set; }
        public string BuildingName { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string PostCode { get; set; }
        public string Telephone { get; set; }
        public Nullable<System.DateTime> PurchaseDate { get; set; }
        public string ManagerName { get; set; }
        public string ManagerTelephone { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<long> LandlordId { get; set; }
    
        public virtual ICollection<damage_intventory> damage_intventory { get; set; }
        public virtual ICollection<paymentHistory> paymentHistories { get; set; }
        public virtual ICollection<tbl_inventory> tbl_inventory { get; set; }
        public virtual ICollection<Property> Properties { get; set; }
    }
}
