//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proptiwise.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommonDocument
    {
        public int CommonDocId { get; set; }
        public string DocName { get; set; }
        public string DocComments { get; set; }
        public Nullable<long> LandLordId { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
    
        public virtual User User { get; set; }
    }
}
