//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proptiwise.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Deposit
    {
        public Deposit()
        {
            this.TenancyDetails = new HashSet<TenancyDetail>();
        }
    
        public int DepositId { get; set; }
        public Nullable<double> DepositAmount { get; set; }
        public Nullable<int> DepositStatus { get; set; }
        public Nullable<int> DepositApproval { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DepositDate { get; set; }
        public Nullable<long> PropertyId { get; set; }
        public Nullable<long> TenantId { get; set; }
        public Nullable<long> LandlordId { get; set; }
        public Nullable<int> OfferId { get; set; }
        public Nullable<int> OfferProposalId { get; set; }
        public Nullable<int> ReqviewId { get; set; }
    
        public virtual Tenant Tenant { get; set; }
        public virtual ICollection<TenancyDetail> TenancyDetails { get; set; }
        public virtual User User { get; set; }
        public virtual Property Property { get; set; }
    }
}
