//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proptiwise.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentType
    {
        public DocumentType()
        {
            this.tblDocuments = new HashSet<tblDocument>();
            this.UserDocuments = new HashSet<UserDocument>();
        }
    
        public int DocumentTypeId { get; set; }
        public string DocumentTypeName { get; set; }
    
        public virtual ICollection<tblDocument> tblDocuments { get; set; }
        public virtual ICollection<UserDocument> UserDocuments { get; set; }
    }
}
