//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proptiwise.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inspection
    {
        public int InspectionId { get; set; }
        public Nullable<long> LandlordId { get; set; }
        public Nullable<long> PropertyId { get; set; }
        public string RoomType { get; set; }
        public string RoomNotes { get; set; }
        public string Images { get; set; }
        public string InspectionNotes { get; set; }
        public string ActionRequired { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<long> TenantId { get; set; }
        public Nullable<int> InspectionStatus { get; set; }
        public Nullable<int> Status { get; set; }
    
        public virtual Tenant Tenant { get; set; }
        public virtual User User { get; set; }
        public virtual Property Property { get; set; }
    }
}
