//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proptiwise.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryImage
    {
        public int ImageId { get; set; }
        public string ImageName { get; set; }
        public Nullable<long> PropertyId { get; set; }
        public Nullable<long> LandlordId { get; set; }
    
        public virtual User User { get; set; }
        public virtual Property Property { get; set; }
    }
}
