//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proptiwise.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class inventory_type
    {
        public inventory_type()
        {
            this.tbl_inventory = new HashSet<tbl_inventory>();
        }
    
        public int InventoryTypeId { get; set; }
        public string InventoryTypeName { get; set; }
    
        public virtual ICollection<tbl_inventory> tbl_inventory { get; set; }
    }
}
