//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proptiwise.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mylist
    {
        public int ListId { get; set; }
        public string ListName { get; set; }
        public Nullable<long> TenantId { get; set; }
        public string ListDetails { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<long> PropertyId { get; set; }
    
        public virtual Tenant Tenant { get; set; }
        public virtual Property Property { get; set; }
    }
}
