//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proptiwise.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class paymentHistory
    {
        public int Paymenthistoryid { get; set; }
        public Nullable<System.DateTime> RecievedOn { get; set; }
        public string Type { get; set; }
        public Nullable<double> Amount { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public string Method { get; set; }
        public string CheckNo { get; set; }
        public Nullable<long> Tenant_Id { get; set; }
        public Nullable<long> Property_Id { get; set; }
        public Nullable<int> Building_Id { get; set; }
        public string Comment { get; set; }
        public Nullable<int> Archievestatus { get; set; }
        public string TransId { get; set; }
        public Nullable<long> Landlord_id { get; set; }
        public string paymentsection { get; set; }
        public Nullable<int> paymentsectionid { get; set; }
        public Nullable<int> ServiceProviderId { get; set; }
        public Nullable<int> ItemNumber { get; set; }
    
        public virtual Building Building { get; set; }
        public virtual Serviceprovider Serviceprovider { get; set; }
        public virtual Tenant Tenant { get; set; }
        public virtual User User { get; set; }
        public virtual Property Property { get; set; }
    }
}
