//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proptiwise.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Plan
    {
        public int PlanID { get; set; }
        public string PlanName { get; set; }
        public string PlanDescription { get; set; }
        public Nullable<System.DateTime> EffectiveDate { get; set; }
        public Nullable<System.DateTime> ExpirationDate { get; set; }
        public Nullable<int> MaxZipCodes { get; set; }
        public Nullable<int> MaxCities { get; set; }
        public Nullable<int> MaxStates { get; set; }
        public Nullable<decimal> PriceMonthly { get; set; }
        public Nullable<decimal> PriceYearly { get; set; }
        public Nullable<bool> Active { get; set; }
    }
}
