//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proptiwise.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class reminderlist
    {
        public int ReminderId { get; set; }
        public Nullable<long> LandlordId { get; set; }
        public Nullable<long> TenantId { get; set; }
        public Nullable<long> PropertyId { get; set; }
        public Nullable<System.DateTime> currentMoveout { get; set; }
    }
}
