//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proptiwise.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RentDue
    {
        public RentDue()
        {
            this.tbl_lease = new HashSet<tbl_lease>();
        }
    
        public int RentDueId { get; set; }
        public string RentDueValue { get; set; }
    
        public virtual ICollection<tbl_lease> tbl_lease { get; set; }
    }
}
