//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proptiwise.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Serviceprovider
    {
        public Serviceprovider()
        {
            this.Faults = new HashSet<Fault>();
            this.paymentHistories = new HashSet<paymentHistory>();
        }
    
        public int ProviderId { get; set; }
        public string ProviderName { get; set; }
        public Nullable<int> ServiceId { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string ZipCode { get; set; }
        public string Address { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Mobile { get; set; }
        public string Password { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> Approval { get; set; }
        public Nullable<long> LandlordId { get; set; }
        public string ProfilePhoto { get; set; }
    
        public virtual ICollection<Fault> Faults { get; set; }
        public virtual ICollection<paymentHistory> paymentHistories { get; set; }
        public virtual service service { get; set; }
        public virtual User User { get; set; }
    }
}
