//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proptiwise.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class setting
    {
        public int id { get; set; }
        public string slug { get; set; }
        public string keyId { get; set; }
        public string value { get; set; }
        public string flagimg { get; set; }
    }
}
