//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proptiwise.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TabRole
    {
        public TabRole()
        {
            this.UserTabPermissions = new HashSet<UserTabPermission>();
        }
    
        public int TabRolesId { get; set; }
        public string TabRolesName { get; set; }
        public string TabRoleUrl { get; set; }
    
        public virtual ICollection<UserTabPermission> UserTabPermissions { get; set; }
    }
}
