//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proptiwise.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_invoice
    {
        public int InvoiceId { get; set; }
        public Nullable<long> PropertyId { get; set; }
        public Nullable<long> TenantId { get; set; }
        public Nullable<double> Amount { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<long> LandlordId { get; set; }
        public Nullable<int> SendStatus { get; set; }
        public Nullable<int> PaymentStatus { get; set; }
        public Nullable<int> AgreementId { get; set; }
        public string Comment { get; set; }
        public Nullable<double> Amountpay { get; set; }

    
        public virtual TenancyAgreement TenancyAgreement { get; set; }
        public virtual Tenant Tenant { get; set; }
        public virtual User User { get; set; }
        public virtual Property Property { get; set; }
    }
}
