//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proptiwise.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_lease
    {
        public tbl_lease()
        {
            this.tbl_LeaseCredits = new HashSet<tbl_LeaseCredits>();
            this.tbl_othercharges = new HashSet<tbl_othercharges>();
        }
    
        public long LeaseId { get; set; }
        public Nullable<long> Property_Id { get; set; }
        public Nullable<long> primaryTenant_Id { get; set; }
        public Nullable<System.DateTime> Startdate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<long> sectenant_Id { get; set; }
        public Nullable<int> term { get; set; }
        public string duration { get; set; }
        public Nullable<double> Rent { get; set; }
        public Nullable<double> balance { get; set; }
        public Nullable<int> rentisdue { get; set; }
        public Nullable<System.DateTime> firstrentalpay { get; set; }
        public Nullable<int> DescriptionId { get; set; }
        public Nullable<double> Amount { get; set; }
        public string Due { get; set; }
        public Nullable<System.DateTime> ValidFrom { get; set; }
        public Nullable<System.DateTime> ValidUntil { get; set; }
        public string Reason { get; set; }
        public string Type { get; set; }
        public Nullable<double> CreditAmount { get; set; }
        public Nullable<System.DateTime> CreditedOn { get; set; }
        public Nullable<bool> LatefeeEnabled { get; set; }
        public Nullable<int> DaysAfterDueDate { get; set; }
        public Nullable<bool> FlatFeeOrBaseAmountOrPercentRent { get; set; }
        public Nullable<double> FlatFee { get; set; }
        public Nullable<double> percentRent { get; set; }
        public Nullable<double> baseAmount { get; set; }
        public Nullable<bool> ExcludeGracePeriod { get; set; }
        public Nullable<double> MaxLateFee { get; set; }
        public Nullable<int> PaymentStatus { get; set; }
        public string Comment { get; set; }
        public string paymentSchedule { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> IsClosed { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public string paymentmode { get; set; }
        public Nullable<System.DateTime> createdOn { get; set; }
        public Nullable<System.DateTime> updatedOn { get; set; }
    
        public virtual Property Property { get; set; }
        public virtual RentDue RentDue { get; set; }
        public virtual Tenant Tenant { get; set; }
        public virtual Tenant Tenant1 { get; set; }
        public virtual ICollection<tbl_LeaseCredits> tbl_LeaseCredits { get; set; }
        public virtual ICollection<tbl_othercharges> tbl_othercharges { get; set; }
    }
}
