//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proptiwise.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_inventory
    {
        public int InventoryId { get; set; }
        public string Name { get; set; }
        public Nullable<int> BuildingId { get; set; }
        public Nullable<long> PropertyId { get; set; }
        public Nullable<int> AreaId { get; set; }
        public string Address { get; set; }
        public Nullable<int> InventoryTypeId { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string Modal { get; set; }
        public string Serial { get; set; }
        public Nullable<double> Cost { get; set; }
        public string Comment { get; set; }
        public string Brand { get; set; }
        public Nullable<long> LandlordId { get; set; }
    
        public virtual Building Building { get; set; }
        public virtual inventory_type inventory_type { get; set; }
        public virtual tbl_area tbl_area { get; set; }
        public virtual User User { get; set; }
        public virtual Property Property { get; set; }
    }
}
