//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proptiwise.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_offer
    {
        public tbl_offer()
        {
            this.TenancyDetails = new HashSet<TenancyDetail>();
        }
    
        public int OfferId { get; set; }
        public Nullable<long> LandlordId { get; set; }
        public Nullable<long> TenantId { get; set; }
        public Nullable<long> PropertyId { get; set; }
        public Nullable<double> Askingprice { get; set; }
        public Nullable<double> offer { get; set; }
        public Nullable<int> OfferStatus { get; set; }
        public Nullable<int> PurposalStatus { get; set; }
        public Nullable<int> Approval { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual Tenant Tenant { get; set; }
        public virtual ICollection<TenancyDetail> TenancyDetails { get; set; }
        public virtual User User { get; set; }
        public virtual Property Property { get; set; }
    }
}
