//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proptiwise.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_othercharges
    {
        public int othercharges_id { get; set; }
        public Nullable<long> lease_id { get; set; }
        public Nullable<long> Property_id { get; set; }
        public Nullable<long> tenant_id { get; set; }
        public string description { get; set; }
        public Nullable<double> amount { get; set; }
        public string due { get; set; }
        public Nullable<System.DateTime> validfrom { get; set; }
        public Nullable<System.DateTime> validuntil { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    
        public virtual Property Property { get; set; }
        public virtual tbl_lease tbl_lease { get; set; }
        public virtual Tenant Tenant { get; set; }
    }
}
