//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proptiwise.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbMessage
    {
        public int MessageId { get; set; }
        public string emailfrom { get; set; }
        public string emailto { get; set; }
        public string Subject { get; set; }
        public string Message { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> SentDate { get; set; }
        public Nullable<System.DateTime> ReceivedDate { get; set; }
    }
}
