//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proptiwise.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tenant
    {
        public Tenant()
        {
            this.damage_intventory = new HashSet<damage_intventory>();
            this.Deposits = new HashSet<Deposit>();
            this.Faults = new HashSet<Fault>();
            this.Inspections = new HashSet<Inspection>();
            this.MovingIns = new HashSet<MovingIn>();
            this.Mylists = new HashSet<Mylist>();
            this.paymentHistories = new HashSet<paymentHistory>();
            this.Purposals = new HashSet<Purposal>();
            this.tbl_invoice = new HashSet<tbl_invoice>();
            this.tbl_offer = new HashSet<tbl_offer>();
            this.TenancyAgreements = new HashSet<TenancyAgreement>();
            this.TenancyDetails = new HashSet<TenancyDetail>();
            this.ViewingPurposals = new HashSet<ViewingPurposal>();
            this.Properties = new HashSet<Property>();
            this.tbl_lease = new HashSet<tbl_lease>();
            this.tbl_lease1 = new HashSet<tbl_lease>();
            this.RequestViews = new HashSet<RequestView>();
            this.tbl_LeaseCredits = new HashSet<tbl_LeaseCredits>();
            this.tbl_othercharges = new HashSet<tbl_othercharges>();
            this.application_details = new HashSet<application_details>();
        }
    
        public long Tenant_Id { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string Telephone { get; set; }
        public string Cellular { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string Gender { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public Nullable<int> Country { get; set; }
        public string PostCode { get; set; }
        public Nullable<System.DateTime> Dateofbirth { get; set; }
        public string DriverLicense { get; set; }
        public string PassportNo { get; set; }
        public string SocialSecurity { get; set; }
        public Nullable<int> Profile { get; set; }
        public Nullable<bool> Smoker { get; set; }
        public Nullable<double> Balance { get; set; }
        public Nullable<System.DateTime> LastPmtOn { get; set; }
        public Nullable<System.DateTime> Nextpmtdue { get; set; }
        public Nullable<System.DateTime> LeaseEnds { get; set; }
        public Nullable<long> Property_Id { get; set; }
        public Nullable<int> leasestatus { get; set; }
        public string Comment { get; set; }
        public string Signature { get; set; }
        public Nullable<long> Landlord_id { get; set; }
        public string ProfilePhoto { get; set; }
        public Nullable<int> MaritalStatus { get; set; }
        public string IfVisa { get; set; }
        public Nullable<short> Pets { get; set; }
        public string ifPets { get; set; }
        public Nullable<short> Children { get; set; }
        public string IfChildren { get; set; }
        public string BuildingName { get; set; }
        public string Town { get; set; }
        public string UnitNumber { get; set; }
        public string Suberb { get; set; }
        public string Province { get; set; }
        public string StreetAddress { get; set; }
        public string Zip { get; set; }
        public string County { get; set; }
    
        public virtual ICollection<damage_intventory> damage_intventory { get; set; }
        public virtual ICollection<Deposit> Deposits { get; set; }
        public virtual ICollection<Fault> Faults { get; set; }
        public virtual ICollection<Inspection> Inspections { get; set; }
        public virtual ICollection<MovingIn> MovingIns { get; set; }
        public virtual ICollection<Mylist> Mylists { get; set; }
        public virtual ICollection<paymentHistory> paymentHistories { get; set; }
        public virtual ICollection<Purposal> Purposals { get; set; }
        public virtual ICollection<tbl_invoice> tbl_invoice { get; set; }
        public virtual ICollection<tbl_offer> tbl_offer { get; set; }
        public virtual ICollection<TenancyAgreement> TenancyAgreements { get; set; }
        public virtual ICollection<TenancyDetail> TenancyDetails { get; set; }
        public virtual ICollection<ViewingPurposal> ViewingPurposals { get; set; }
        public virtual ICollection<Property> Properties { get; set; }
        public virtual Property Property { get; set; }
        public virtual ICollection<tbl_lease> tbl_lease { get; set; }
        public virtual ICollection<tbl_lease> tbl_lease1 { get; set; }
        public virtual ICollection<RequestView> RequestViews { get; set; }
        public virtual ICollection<tbl_LeaseCredits> tbl_LeaseCredits { get; set; }
        public virtual ICollection<tbl_othercharges> tbl_othercharges { get; set; }
        public virtual ICollection<application_details> application_details { get; set; }
    }
}
