//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proptiwise.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.CommonDocuments = new HashSet<CommonDocument>();
            this.damage_intventory = new HashSet<damage_intventory>();
            this.Deposits = new HashSet<Deposit>();
            this.Faults = new HashSet<Fault>();
            this.Inspections = new HashSet<Inspection>();
            this.InventoryImages = new HashSet<InventoryImage>();
            this.MovingIns = new HashSet<MovingIn>();
            this.paymentHistories = new HashSet<paymentHistory>();
            this.PropertyImages = new HashSet<PropertyImage>();
            this.Purposals = new HashSet<Purposal>();
            this.Serviceproviders = new HashSet<Serviceprovider>();
            this.services = new HashSet<service>();
            this.tbl_inventory = new HashSet<tbl_inventory>();
            this.tbl_invoice = new HashSet<tbl_invoice>();
            this.tbl_offer = new HashSet<tbl_offer>();
            this.TenancyAgreements = new HashSet<TenancyAgreement>();
            this.TenancyDetails = new HashSet<TenancyDetail>();
            this.UserDocuments = new HashSet<UserDocument>();
            this.UserReportsPermissions = new HashSet<UserReportsPermission>();
            this.UserTabPermissions = new HashSet<UserTabPermission>();
            this.ViewingPurposals = new HashSet<ViewingPurposal>();
            this.Properties = new HashSet<Property>();
            this.RequestViews = new HashSet<RequestView>();
            this.application_details = new HashSet<application_details>();
        }
    
        public long UserID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string CompanyName { get; set; }
        public string Email { get; set; }
        public string Address1 { get; set; }
        public string City { get; set; }
        public Nullable<int> Country { get; set; }
        public string County { get; set; }
        public string Zip { get; set; }
        public string Phone { get; set; }
        public string Mobile { get; set; }
        public string Password { get; set; }
        public Nullable<int> UserTypeID { get; set; }
        public Nullable<int> UserStatusID { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string TimeZone { get; set; }
        public Nullable<bool> AgreedToTerms { get; set; }
        public string Terms { get; set; }
        public Nullable<int> CCType { get; set; }
        public string CCNo { get; set; }
        public string CCExpDate { get; set; }
        public string CCSecurityNo { get; set; }
        public Nullable<bool> BillingAddressSameAsCase { get; set; }
        public string BillingAddress { get; set; }
        public string BillingCity { get; set; }
        public string BillingState { get; set; }
        public string BillingZip { get; set; }
        public string NameOnAccount { get; set; }
        public string UserName { get; set; }
        public string Address2 { get; set; }
        public string State { get; set; }
        public Nullable<int> UserRole { get; set; }
        public string Signature { get; set; }
        public string photo { get; set; }
        public Nullable<int> RoleId { get; set; }
        public string ProfilePhoto { get; set; }
        public string Town { get; set; }
        public string BuildingName { get; set; }
        public string UnitNumber { get; set; }
        public string Suberb { get; set; }
        public string Province { get; set; }
        public string StreetAddress { get; set; }
        public string PostCode { get; set; }
        public string StripeCustomerId { get; set; }
        public Nullable<long> UserLandlordId { get; set; }
    
        public virtual ICollection<CommonDocument> CommonDocuments { get; set; }
        public virtual Country Country1 { get; set; }
        public virtual ICollection<damage_intventory> damage_intventory { get; set; }
        public virtual ICollection<Deposit> Deposits { get; set; }
        public virtual ICollection<Fault> Faults { get; set; }
        public virtual ICollection<Inspection> Inspections { get; set; }
        public virtual ICollection<InventoryImage> InventoryImages { get; set; }
        public virtual ICollection<MovingIn> MovingIns { get; set; }
        public virtual ICollection<paymentHistory> paymentHistories { get; set; }
        public virtual ICollection<PropertyImage> PropertyImages { get; set; }
        public virtual ICollection<Purposal> Purposals { get; set; }
        public virtual ICollection<Serviceprovider> Serviceproviders { get; set; }
        public virtual ICollection<service> services { get; set; }
        public virtual ICollection<tbl_inventory> tbl_inventory { get; set; }
        public virtual ICollection<tbl_invoice> tbl_invoice { get; set; }
        public virtual ICollection<tbl_offer> tbl_offer { get; set; }
        public virtual ICollection<TenancyAgreement> TenancyAgreements { get; set; }
        public virtual ICollection<TenancyDetail> TenancyDetails { get; set; }
        public virtual ICollection<UserDocument> UserDocuments { get; set; }
        public virtual ICollection<UserReportsPermission> UserReportsPermissions { get; set; }
        public virtual UserRole UserRole1 { get; set; }
        public virtual ICollection<UserTabPermission> UserTabPermissions { get; set; }
        public virtual ICollection<ViewingPurposal> ViewingPurposals { get; set; }
        public virtual ICollection<Property> Properties { get; set; }
        public virtual ICollection<RequestView> RequestViews { get; set; }
        public virtual ICollection<application_details> application_details { get; set; }
    }
}
