//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proptiwise.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserTabPermission
    {
        public int UserTabPermissionsId { get; set; }
        public Nullable<long> UserId { get; set; }
        public Nullable<int> TabRoleId { get; set; }
        public Nullable<int> PermissionStatus { get; set; }
    
        public virtual TabRole TabRole { get; set; }
        public virtual User User { get; set; }
    }
}
