//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proptiwise.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewingPurposal
    {
        public ViewingPurposal()
        {
            this.TenancyDetails = new HashSet<TenancyDetail>();
        }
    
        public int ViewingPurposalid { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Phone { get; set; }
        public Nullable<System.DateTime> PreferredDate { get; set; }
        public string PreferredTime { get; set; }
        public string text { get; set; }
        public Nullable<int> Approve { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<long> TenantId { get; set; }
        public Nullable<long> LandlordId { get; set; }
        public Nullable<long> PropertyId { get; set; }
        public Nullable<int> RequestViewid { get; set; }
    
        public virtual ICollection<TenancyDetail> TenancyDetails { get; set; }
        public virtual Tenant Tenant { get; set; }
        public virtual User User { get; set; }
        public virtual Property Property { get; set; }
    }
}
